declare var HOME_WINDOW_WEBPACK_ENTRY: string;
declare var HOME_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare var OVERLAY_WINDOW_WEBPACK_ENTRY: string;
declare var OVERLAY_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
